services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
      POSTGRES_DB: himdrishti
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d

  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD:-root}@postgres:5432/himdrishti
      - JWT_SECRET=${JWT_SECRET:-a484fb64a98505b75edc6515ed2e59774a6f5f819b3692026077395f30577398}
      - MODEL1_URL=http://model1:8001
      - MODEL2_URL=http://model2:8002
      - MODEL3_URL=http://model3:8003
    depends_on:
      - postgres

  model1:
    build: ./backend/model1-seaice-service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD:-root}@postgres:5432/himdrishti
    volumes:
      - ./ml/artifacts:/app/artifacts
    depends_on:
      - postgres

  model2:
    build: ./backend/model2-iceberg-service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD:-root}@postgres:5432/himdrishti
    volumes:
      - ./ml/artifacts:/app/artifacts
    depends_on:
      - postgres

  model3:
    build: ./backend/model3-routing-service
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD:-root}@postgres:5432/himdrishti
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway

volumes:
  pgdata:
